name: (CI)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'output/**'
    branches:
       - "main"
       
   

defaults:
  run:
    shell: bash

jobs:
   CI:
    runs-on: [ ubuntu-latest ]
    name: Gated Build
    steps:
      
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: test script
        run: |
          git pull
          upload.sh output/
          ls;
          cd policies;
          ls;
          echo "${{secrets.AZURE_PUB}}"
        
     
